/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import DAO.UsuarioDAO;
import DTO.UsuarioDTO;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author 823157005
 */
public class CadastroTela extends javax.swing.JFrame {
    public boolean Preenchido(){
       
        if(textNome.getText().isEmpty()||textEmail.getText().isEmpty()||textTelefone.getText().isEmpty()||textSenha.getText().isEmpty()){
            return false;
        } else {
            return true;
        }
    }
    
    MaskFormatter mfTelefone;
    
    
    
    /**
     * Creates new form TelaCadastro
     */
    
    
    
    public CadastroTela() {
        try {
            mfTelefone = new MaskFormatter("(##)#####-####");
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Telefone Inválido: " +ex);
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textTelefone = new javax.swing.JFormattedTextField(mfTelefone);
        textEmail = new javax.swing.JTextField();
        textNome = new javax.swing.JTextField();
        textSenha = new javax.swing.JPasswordField();
        cadastroButton = new javax.swing.JButton();
        loginButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textTelefone.setBackground(new java.awt.Color(217, 217, 217));
        textTelefone.setBorder(null);
        textTelefone.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(textTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 300, 210, 50));

        textEmail.setBackground(new java.awt.Color(217, 217, 217));
        textEmail.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        textEmail.setToolTipText("");
        textEmail.setBorder(null);
        textEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textEmailActionPerformed(evt);
            }
        });
        getContentPane().add(textEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 219, 230, 50));

        textNome.setBackground(new java.awt.Color(217, 217, 217));
        textNome.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        textNome.setToolTipText("");
        textNome.setBorder(null);
        textNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNomeActionPerformed(evt);
            }
        });
        getContentPane().add(textNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 139, 220, 50));

        textSenha.setBackground(new java.awt.Color(217, 217, 217));
        textSenha.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        textSenha.setBorder(null);
        textSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(textSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 380, 230, 50));

        cadastroButton.setBorder(null);
        cadastroButton.setContentAreaFilled(false);
        cadastroButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cadastroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cadastroButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 470, 200, 40));

        loginButton.setBorder(null);
        loginButton.setContentAreaFilled(false);
        loginButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        getContentPane().add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 150, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VIEW/Image/telaCadastro.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNomeActionPerformed

    private void cadastroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroButtonActionPerformed
        if(this.Preenchido()){
            String nome = textNome.getText();
            String email = textEmail.getText();
            String telefone = textTelefone.getText();
            String senha = textSenha.getText();
            UsuarioDTO usuario = new UsuarioDTO(nome, senha, email, telefone);
            UsuarioDAO dao = new UsuarioDAO();
            try {
                if(dao.existeEmail(usuario)){
                    JOptionPane.showMessageDialog(null, "Email já cadastrado");
                }
                else {
                    dao.adicionarUsuario(nome, email, senha, telefone);
                    JOptionPane.showMessageDialog(null, "Usuário cadastrado com sucesso");
                    DashboardTela ds = new DashboardTela();
                    ds.setVisible(true);
                    this.dispose();
                }
            } catch (Exception ex) {
                Logger.getLogger(CadastroTela.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        
        } else {
        JOptionPane.showMessageDialog(null, "Para efetuar o seu cadastro, todos os campos são obrigatórios");
        }
    }//GEN-LAST:event_cadastroButtonActionPerformed

    private void textSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textSenhaActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
   
        LoginTela login = new LoginTela();
        login.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_loginButtonActionPerformed

    private void textEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textEmailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastroButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton loginButton;
    private javax.swing.JTextField textEmail;
    private javax.swing.JTextField textNome;
    private javax.swing.JPasswordField textSenha;
    private javax.swing.JFormattedTextField textTelefone;
    // End of variables declaration//GEN-END:variables
}
