/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

/**
 *
 * @author 823157005
 */
public class DashboardTela extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard_Usuario
     */
    public DashboardTela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        creditosButton = new javax.swing.JButton();
        novoProjetoButton = new javax.swing.JButton();
        meusProjetosButton = new javax.swing.JButton();
        explorarButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        creditosButton.setBorder(null);
        creditosButton.setContentAreaFilled(false);
        creditosButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        creditosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditosButtonActionPerformed(evt);
            }
        });
        getContentPane().add(creditosButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 490, 230, 60));

        novoProjetoButton.setBorder(null);
        novoProjetoButton.setContentAreaFilled(false);
        novoProjetoButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        novoProjetoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoProjetoButtonActionPerformed(evt);
            }
        });
        getContentPane().add(novoProjetoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 550, 80));

        meusProjetosButton.setBorder(null);
        meusProjetosButton.setContentAreaFilled(false);
        meusProjetosButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        meusProjetosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meusProjetosButtonActionPerformed(evt);
            }
        });
        getContentPane().add(meusProjetosButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 550, 70));

        explorarButton.setBorder(null);
        explorarButton.setBorderPainted(false);
        explorarButton.setContentAreaFilled(false);
        explorarButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        explorarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                explorarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(explorarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, 540, 80));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VIEW/Image/1.png"))); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(1048, 591));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void creditosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditosButtonActionPerformed
        SobreNosTela sb = new SobreNosTela();
        sb.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_creditosButtonActionPerformed

    private void novoProjetoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoProjetoButtonActionPerformed
        NovoProjetoTela novoProjeto = new NovoProjetoTela();
        novoProjeto.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_novoProjetoButtonActionPerformed

    private void meusProjetosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meusProjetosButtonActionPerformed
        MeusProjetosTela projetos = new MeusProjetosTela();
        projetos.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_meusProjetosButtonActionPerformed

    private void explorarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_explorarButtonActionPerformed
       ExplorarProjetosTela tc = new ExplorarProjetosTela();
       tc.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_explorarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton creditosButton;
    private javax.swing.JButton explorarButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton meusProjetosButton;
    private javax.swing.JButton novoProjetoButton;
    // End of variables declaration//GEN-END:variables
}
