/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import DAO.ProjetoDAO;
import DTO.ProjetoDTO;
import java.text.ParseException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author 823157005
 */
public class ExplorarProjetosTela extends javax.swing.JFrame {
    MaskFormatter mfData;
    MaskFormatter mfTelefone;
    /**
     * Creates new form telaProjetos
     */
    public ExplorarProjetosTela() {
        /*
        try {
            mfTelefone = new MaskFormatter("(##)#####-####");
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Telefone Inválido: " +ex);
        }
        
        try {
            mfData = new MaskFormatter("##/##/####");
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Data Inválida: " +ex);
        }
        */
        initComponents();
        buscarProjetos();
        setLocationRelativeTo(null);
    }
    private void buscarProjetos() {
        try {
            ProjetoDAO dao = new ProjetoDAO();
            ProjetoDTO[] projetos = dao.obterProjeto();
            projetosComboBox.setModel(new DefaultComboBoxModel<>(projetos));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Projeto não encontrado, tente novamente mais tarde.");
            e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVoltar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        projetosComboBox = new javax.swing.JComboBox<>();
        textTelefone = new javax.swing.JFormattedTextField(mfTelefone);
        textData = new javax.swing.JFormattedTextField(mfData);
        jLabel2 = new javax.swing.JLabel();
        nomeTextField = new javax.swing.JTextField();
        codigoTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        descricaoTextArea = new javax.swing.JTextArea();
        odsTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        statusTextField = new javax.swing.JTextField();
        responsavelTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVoltar.setBorder(null);
        btnVoltar.setBorderPainted(false);
        btnVoltar.setContentAreaFilled(false);
        btnVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 40, 40));

        btnCancelar.setBorder(null);
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 480, 200, 60));

        btnConsultar.setBorder(null);
        btnConsultar.setContentAreaFilled(false);
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 480, 220, 60));

        getContentPane().add(projetosComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 810, 60));

        textTelefone.setBackground(new java.awt.Color(217, 217, 217));
        textTelefone.setBorder(null);
        textTelefone.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(textTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 320, 330, 40));

        textData.setBackground(new java.awt.Color(217, 217, 217));
        textData.setBorder(null);
        textData.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        textData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textDataActionPerformed(evt);
            }
        });
        getContentPane().add(textData, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 400, 370, 50));

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Nome");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 80, 40));
        getContentPane().add(nomeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 172, 350, 40));
        getContentPane().add(codigoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 340, 40));

        descricaoTextArea.setColumns(20);
        descricaoTextArea.setRows(5);
        jScrollPane1.setViewportView(descricaoTextArea);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 330, 130));
        getContentPane().add(odsTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 490, 280, 40));

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Status");
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 170, 90, 40));
        getContentPane().add(statusTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 172, 310, 40));
        getContentPane().add(responsavelTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 230, 300, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VIEW/Image/consultar-projetos.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(1048, 591));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        DashboardTela ds = new DashboardTela();
        ds.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        ProjetoDAO dao = new ProjetoDAO();
        ProjetoDTO projeto = new ProjetoDTO();
        try {
            projeto = dao.consultarProjeto(projeto, codigoTextField.getText());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro consulta: " + ex);
        }
        nomeTextField.setText(projeto.getNome_projeto());
        odsTextField.setText(projeto.getOds_projeto());
        descricaoTextArea.setText(projeto.getDescricao());
        codigoTextField.setText(String.valueOf(projeto.getCod_projeto()));
        responsavelTextField.setText(projeto.getNome_responsavel());
        textTelefone.setText(projeto.getTelefone_responsavel());
        textData.setText(projeto.getData_criacao());
        statusTextField.setText(projeto.getStatus_projeto());
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        nomeTextField.setText("");
        odsTextField.setText("");
        descricaoTextArea.setText("");
        codigoTextField.setText("");
        responsavelTextField.setText("");
        textTelefone.setText("");
        textData.setText("");
        statusTextField.setText("");
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void textDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textDataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExplorarProjetosTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExplorarProjetosTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExplorarProjetosTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExplorarProjetosTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExplorarProjetosTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JTextField codigoTextField;
    private javax.swing.JTextArea descricaoTextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nomeTextField;
    private javax.swing.JTextField odsTextField;
    private javax.swing.JComboBox<ProjetoDTO> projetosComboBox;
    private javax.swing.JTextField responsavelTextField;
    private javax.swing.JTextField statusTextField;
    private javax.swing.JFormattedTextField textData;
    private javax.swing.JFormattedTextField textTelefone;
    // End of variables declaration//GEN-END:variables
}
