/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

import DAO.ConexaoDAO;
import DAO.ProjetoDAO;
import DTO.ProjetoDTO;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.DefaultComboBoxModel;

import javax.swing.JOptionPane;
/**
 *
 * @author danil
 */
public class ProjetoTelaAdmin extends javax.swing.JFrame {

    /**
     * Creates new form ProjetoTela
     */
    public ProjetoTelaAdmin() {
        super ("Projetos");
        initComponents();
        buscarProjetos();
        setLocationRelativeTo(null);
    }

    private void buscarProjetos() {
        try {
            ProjetoDAO dao = new ProjetoDAO();
            ProjetoDTO[] projetos = dao.obterProjeto();
            projetosComboBox.setModel(new DefaultComboBoxModel<>(projetos));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Projeto não encontrado, tente novamente mais tarde.");
            e.printStackTrace();
        }
    }
    
    private boolean Preenchido(){
       
        if(nomeProjetoTextField.getText().isEmpty()||odsProjetoTextField.getText().isEmpty()||descricaoTextPane.getText().isEmpty()||
                nomeResponsavelTextField.getText().isEmpty()||telefoneResponsavelTextField.getText().isEmpty()||
                dataCriacaoTextField.getText().isEmpty()||statusTextField.getText().isEmpty()){
            return false;
        } else {
            return true;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        projetoAdminPanel = new javax.swing.JPanel();
        projetosComboBox = new javax.swing.JComboBox<>();
        idProjetoTextField = new javax.swing.JTextField();
        nomeProjetoTextField = new javax.swing.JTextField();
        odsProjetoTextField = new javax.swing.JTextField();
        nomeResponsavelTextField = new javax.swing.JTextField();
        novoButton = new javax.swing.JButton();
        atualizarButton = new javax.swing.JButton();
        removerButton = new javax.swing.JButton();
        cancelarButton = new javax.swing.JButton();
        voltarButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        descricaoTextPane = new javax.swing.JTextPane();
        telefoneResponsavelTextField = new javax.swing.JTextField();
        dataCriacaoTextField = new javax.swing.JTextField();
        statusTextField = new javax.swing.JTextField();
        consultarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        projetoAdminPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Gerenciar Projetos"));

        projetosComboBox.setMaximumRowCount(50);

        idProjetoTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Id"));
        idProjetoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idProjetoTextFieldActionPerformed(evt);
            }
        });

        nomeProjetoTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Nome do Projeto"));
        nomeProjetoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeProjetoTextFieldActionPerformed(evt);
            }
        });

        odsProjetoTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("ODS"));
        odsProjetoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                odsProjetoTextFieldActionPerformed(evt);
            }
        });

        nomeResponsavelTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Nome do responsavel"));
        nomeResponsavelTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeResponsavelTextFieldActionPerformed(evt);
            }
        });

        novoButton.setText("Novo");
        novoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoButtonActionPerformed(evt);
            }
        });

        atualizarButton.setText("Atualizar");
        atualizarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarButtonActionPerformed(evt);
            }
        });

        removerButton.setText("Remover");
        removerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerButtonActionPerformed(evt);
            }
        });

        cancelarButton.setText("Cancelar");
        cancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarButtonActionPerformed(evt);
            }
        });

        voltarButton.setText("Voltar");
        voltarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarButtonActionPerformed(evt);
            }
        });

        descricaoTextPane.setBorder(javax.swing.BorderFactory.createTitledBorder("Descricao"));
        jScrollPane1.setViewportView(descricaoTextPane);

        telefoneResponsavelTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Telefone do responsavel"));
        telefoneResponsavelTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefoneResponsavelTextFieldActionPerformed(evt);
            }
        });

        dataCriacaoTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Data de criacao"));

        statusTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Status"));

        consultarButton.setText("Consultar");
        consultarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout projetoAdminPanelLayout = new javax.swing.GroupLayout(projetoAdminPanel);
        projetoAdminPanel.setLayout(projetoAdminPanelLayout);
        projetoAdminPanelLayout.setHorizontalGroup(
            projetoAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(projetoAdminPanelLayout.createSequentialGroup()
                .addGroup(projetoAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, projetoAdminPanelLayout.createSequentialGroup()
                        .addComponent(idProjetoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nomeProjetoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(odsProjetoTextField))
                    .addComponent(projetosComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(projetoAdminPanelLayout.createSequentialGroup()
                        .addGroup(projetoAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomeResponsavelTextField)
                            .addComponent(dataCriacaoTextField))
                        .addGap(18, 18, 18)
                        .addGroup(projetoAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(telefoneResponsavelTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                            .addComponent(statusTextField)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, projetoAdminPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(projetoAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(consultarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(removerButton, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                        .addGap(31, 31, 31)
                        .addGroup(projetoAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cancelarButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(novoButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addGroup(projetoAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(voltarButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(atualizarButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(24, 24, 24))
        );
        projetoAdminPanelLayout.setVerticalGroup(
            projetoAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(projetoAdminPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(projetosComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(projetoAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idProjetoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeProjetoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(odsProjetoTextField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(projetoAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nomeResponsavelTextField)
                    .addComponent(telefoneResponsavelTextField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(projetoAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(statusTextField)
                    .addComponent(dataCriacaoTextField))
                .addGap(18, 18, 18)
                .addGroup(projetoAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(projetoAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(atualizarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(novoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(consultarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(projetoAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(voltarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(projetoAdminPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(projetoAdminPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomeProjetoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeProjetoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeProjetoTextFieldActionPerformed

    private void odsProjetoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_odsProjetoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_odsProjetoTextFieldActionPerformed

    private void voltarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarButtonActionPerformed
                    DashboardAdminTela vs = new DashboardAdminTela();
                    vs.setVisible(true);
                    this.dispose();
    }//GEN-LAST:event_voltarButtonActionPerformed

    private void idProjetoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idProjetoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idProjetoTextFieldActionPerformed

    private void novoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoButtonActionPerformed
       if(this.Preenchido()){
            String nomeProjeto = nomeProjetoTextField.getText();
            String ods = odsProjetoTextField.getText();
            String descricao = descricaoTextPane.getText();
            String nomeResponsavel = nomeResponsavelTextField.getText();
            String telefone = telefoneResponsavelTextField.getText();
            String dataCriacao = dataCriacaoTextField.getText();
            String status = statusTextField.getText();
            ProjetoDAO dao = new ProjetoDAO();
            dao.adicionarProjeto(nomeProjeto, descricao, ods, nomeResponsavel, telefone, dataCriacao, status);
            JOptionPane.showMessageDialog(null, "Projeto cadastrado com sucesso");
            buscarProjetos();
        } else {
        JOptionPane.showMessageDialog(null, "Para efetuar o cadastro do projeto, todos os campos são obrigatórios"+
                " exceto o de id");
        }
    }//GEN-LAST:event_novoButtonActionPerformed

    private void removerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerButtonActionPerformed
        String id = idProjetoTextField.getText();
        ProjetoDAO dao = new ProjetoDAO();
        dao.removerProjeto(id);
        buscarProjetos();
        idProjetoTextField.setText("");
    }//GEN-LAST:event_removerButtonActionPerformed

    private void atualizarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarButtonActionPerformed
        String id = idProjetoTextField.getText();
        String nomeProjeto = nomeProjetoTextField.getText();
        String ods = odsProjetoTextField.getText();
        String descricao = descricaoTextPane.getText();
        String nomeResponsavel = nomeResponsavelTextField.getText();
        String telefone = telefoneResponsavelTextField.getText();
        String dataCriacao = dataCriacaoTextField.getText();
        String status = statusTextField.getText();
        ProjetoDAO dao = new ProjetoDAO();
        dao.atualizarProjeto(id, nomeProjeto, descricao, ods, nomeResponsavel, telefone, dataCriacao, status);
        buscarProjetos();
        nomeProjetoTextField.setText("");
        odsProjetoTextField.setText("");
        descricaoTextPane.setText("");
        idProjetoTextField.setText("");
        nomeResponsavelTextField.setText("");
        telefoneResponsavelTextField.setText("");
        dataCriacaoTextField.setText("");
        statusTextField.setText("");
    }//GEN-LAST:event_atualizarButtonActionPerformed

    private void cancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarButtonActionPerformed
        nomeProjetoTextField.setText("");
        odsProjetoTextField.setText("");
        descricaoTextPane.setText("");
        idProjetoTextField.setText("");
        nomeResponsavelTextField.setText("");
        telefoneResponsavelTextField.setText("");
        dataCriacaoTextField.setText("");
        statusTextField.setText("");
    }//GEN-LAST:event_cancelarButtonActionPerformed

    private void nomeResponsavelTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeResponsavelTextFieldActionPerformed
        //odsProjetoTextFielding code here:
    }//GEN-LAST:event_nomeResponsavelTextFieldActionPerformed

    private void telefoneResponsavelTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefoneResponsavelTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefoneResponsavelTextFieldActionPerformed

    private void consultarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarButtonActionPerformed
        ProjetoDAO dao = new ProjetoDAO();
        ProjetoDTO projeto = new ProjetoDTO();
        try {
            projeto = dao.consultarProjeto(projeto, idProjetoTextField.getText());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro consulta: " + ex);
        }
        nomeProjetoTextField.setText(projeto.getNome_projeto());
        odsProjetoTextField.setText(projeto.getOds_projeto());
        descricaoTextPane.setText(projeto.getDescricao());
        idProjetoTextField.setText(String.valueOf(projeto.getCod_projeto()));
        nomeResponsavelTextField.setText(projeto.getNome_responsavel());
        telefoneResponsavelTextField.setText(projeto.getTelefone_responsavel());
        dataCriacaoTextField.setText(projeto.getData_criacao());
        statusTextField.setText(projeto.getStatus_projeto());
    }//GEN-LAST:event_consultarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjetoTelaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjetoTelaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjetoTelaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjetoTelaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProjetoTelaAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atualizarButton;
    private javax.swing.JButton cancelarButton;
    private javax.swing.JButton consultarButton;
    private javax.swing.JTextField dataCriacaoTextField;
    private javax.swing.JTextPane descricaoTextPane;
    private javax.swing.JTextField idProjetoTextField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nomeProjetoTextField;
    private javax.swing.JTextField nomeResponsavelTextField;
    private javax.swing.JButton novoButton;
    private javax.swing.JTextField odsProjetoTextField;
    private javax.swing.JPanel projetoAdminPanel;
    private javax.swing.JComboBox<ProjetoDTO> projetosComboBox;
    private javax.swing.JButton removerButton;
    private javax.swing.JTextField statusTextField;
    private javax.swing.JTextField telefoneResponsavelTextField;
    private javax.swing.JButton voltarButton;
    // End of variables declaration//GEN-END:variables
}
